#ifndef VGM_H
#define VGM_H

typedef struct _vgm_header {
    char vgm[4];
    unsigned long eof_offset;
    unsigned long version;
    unsigned long sn76489_clock;
    unsigned long ym2413_clock;
    unsigned long gd3_offset;
    unsigned long total_sample_count;
    unsigned long loop_offset;
    unsigned long loop_samples_count;
    unsigned long rate;
    unsigned short sn_fb;
    unsigned char snw;
    unsigned char sf;
    unsigned long ym2612_clock;
    unsigned long ym2151_clock;
    unsigned long vgm_data_offset;
    unsigned long sega_pcm_clock;
    unsigned long spcm_longerface;
    unsigned long rf5c68_clock;
    unsigned long ym2203_clock;
    unsigned long ym2608_clock;
    unsigned long ym2610_clock;
    unsigned long ym3812_clock;
    unsigned long ym3526_clock;
    unsigned long y8950_clock;
    unsigned long ymf262_clock;
    unsigned long ymf278b_clock;
    unsigned long ymf271_clock;
    unsigned long ymz280b_clock;
    unsigned long rf5c164_clock;
    unsigned long pwm_clock;
    unsigned long ay8910_clock;
    unsigned char ayt;
    unsigned char ay_flags[3];
    unsigned char vm;
    unsigned char padding0;
    unsigned char lb;
    unsigned char lm;
    unsigned long gb_dmg_clock;
    unsigned long nes_apu_clock;
    unsigned long multipcm_clock;
    unsigned long upd7759_clock;
    unsigned long okim6258_clock;
    unsigned char of;
    unsigned char kf;
    unsigned char cf;
    unsigned char padding1;
    unsigned long okim6395_clock;
    unsigned long k051649_clock;
    unsigned long k054539_clock;
    unsigned long huc6280_clock;
    unsigned long c140_clock;
    unsigned long k053260_clock;
    unsigned long pokey_clock;
    unsigned long qsound_clock;
    unsigned long scsp_clock;
    unsigned long extra_hdr_ofs;
    unsigned long wonderswan_clock;
    unsigned long vsu_clock;
    unsigned long saa1099_clock;
    unsigned long es5503_clock;
    unsigned long es5506_clock;
    unsigned short es_chns;
    unsigned char cd;
    unsigned char padding2;
    unsigned long x1010_clock;
    unsigned long c352_clock;
    unsigned long ga20_clock;
    unsigned long mikey_clock;
    unsigned long padding3[6];
} vgm_header_t;

#endif